# Permalinks

# Setup
title: David Březina
description: Personal website of David Březina
url: https://mrbrezina.com
baseurl: ""

# About/contact
author:
  name: David Březina
  url: https://mrbrezina.com
  email: hellow@mrbrezina.com

# Build settings
markdown: kramdown
