# Permalinks

# Setup
title: David Březina
description: Personal website of David Březina
url: https://mrbrezina.com
baseurl: ""

# About/contact
author:
  name: David Březina
  url: https://mrbrezina.com
  email: hellow@mrbrezina.com

# Build settings
markdown: kramdown

# The default sharing image for sharing any page to social media. If a post has
# a "sharing_image" meta that will be used instead
# Use a relative path from the root of the project!
sharing_image: /assets/sharing_image.png
