# Permalinks

# Setup
title: MrBrezina
description: Personal website of David Březina
url: https://www.mrbrezina.com
baseurl: ""

# About/contact
author:
  name: David Březina
  url: https://www.mrbrezina.com
  email: brezina@davi.cz

# Build settings
markdown: kramdown
